// UI copy, word for word from the specs' UI Copy tables:
// specs/features/2026-09-14-create-poll.md and specs/features/2026-09-15-share-and-join-poll.md.
export const COPY = {
  app: {
    name: 'Polls',
  },
  landing: {
    heading: 'Welcome',
    intro: 'Create a poll and share it with others.',
    createButton: 'Create poll',
  },
  form: {
    heading: 'Create a poll',
    questionLabel: 'Question',
    questionPlaceholder: 'What do you want to ask?',
    addDetails: 'Add details',
    detailsLabel: 'Details (optional)',
    detailsPlaceholder: 'Add context for the people answering.',
    removeDetails: 'Remove details',
    answerTypeLabel: 'Answer type',
    singleChoice: 'Single choice — people pick one answer',
    multipleChoice: 'Multiple choice — people can pick more than one answer',
    optionsLabel: 'Options',
    optionsHelper: 'Add 2 to 8 options. Drag to reorder.',
    optionPlaceholder: (n) => `Option ${n}`,
    dragHandleLabel: (n) => `Drag to reorder option ${n}`,
    removeOptionLabel: (n) => `Remove option ${n}`,
    addOption: 'Add option',
    addOptionHint: 'You can add up to 8 options.',
    createButton: 'Create poll',
    creatingButton: 'Creating…',
    cancelButton: 'Cancel',
  },
  counter: (count, max) => `${count}/${max}`,
  errors: {
    questionEmpty: 'Enter a question.',
    optionEmpty: 'Fill in this option or remove it.',
    optionDuplicate: 'This option is already in the list.',
    saveFailed: "Couldn't create your poll. Check your connection and try again.",
  },
  discardDialog: {
    title: 'Discard this poll?',
    body: "What you've entered will be lost.",
    discard: 'Discard',
    keepEditing: 'Keep editing',
  },
  confirmation: {
    heading: 'Poll created',
    intro: 'Your poll is open and ready for answers.',
    answerType: {
      single: 'Single choice',
      multiple: 'Multiple choice',
    },
    status: {
      open: 'Open',
    },
    backHome: 'Back to home',
    createAnother: 'Create another poll',
    loading: 'Loading poll…',
    loadError: "We couldn't load this poll.",
  },
  share: {
    sharePoll: 'Share poll',
    title: 'Invite people',
    body: 'Anyone with this link can join and answer your poll.',
    copy: 'Copy',
    copied: 'Copied',
    copiedAnnouncement: 'Link copied',
    copyError: "Couldn't copy the link. Select it and copy it yourself.",
    shareLink: 'Share link',
    shareText: (link) => `Answer my poll here: ${link}`,
    done: 'Done',
    close: 'Close',
  },
  inviteLink: {
    label: 'Invite link',
    brokenHeading: "This link doesn't work",
    brokenBody: 'It may be mistyped or incomplete. Ask the person who shared it for a new link.',
  },
  invite: {
    eyebrow: "You're invited",
    optionCount: (n) => `${n} options`,
    loading: 'Loading poll…',
    loadError: "We couldn't load this poll.",
    loadErrorBody: 'Check your connection and try again.',
    tryAgain: 'Try again',
  },
  join: {
    nicknameLabel: 'Your nickname',
    nicknamePlaceholder: 'e.g. Noa',
    nicknameHelp: "The poll's creator will see this name.",
    joinButton: 'Join poll',
    joiningButton: 'Joining…',
    nicknameEmpty: 'Enter a nickname.',
    nicknameTaken: 'This nickname is taken in this poll. Try another one.',
    joinFailed: "Couldn't join the poll. Check your connection and try again.",
  },
  joined: {
    // "You're in, {nickname}": the page renders the nickname after this, isolated in <bdi>.
    headingPrefix: "You're in, ",
  },
};
